require("options")
require("keymaps")
require("plugins")
require("colorscheme")
require("lsp")
require("config.nvim-tree")
require("discordrpc")
require("github-copilot")
require("neoscroll").setup()
require("lualine").setup() -- https://github.com/nvim-lualine/lualine.nvim
